### ISSUE TITLE
Roadmap: 3.x

### ISSUE THREAD

**Issue by kgriffs** [falconry/falcon#1894]
# Roadmap for 3.x

(WIP)

### ASGI

* Refine the implementation
* Affordances to support common SSE, WebSocket patterns (e.g., detecting closed SSE connection)
* Ecosystem integrations. https://github.com/falconry/falcon/discussions/1932 

### Frequently requested "missing" features

* AuthN/Z: Affordances to support JWT, OAuth2 workflows and POLP/RBAC. Provide building blocks that can be composed to provide custom auth, Okta flows, Google OAuth2, etc. (with accompanying documented recipes  (see also: https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/ and https://developer.okta.com/docs/concepts/oauth-openid/ and https://portswigger.net/research/hidden-oauth-attack-vectors and https://www.torocloud.com/podcast/oauth-web-api-security-matthias-biehl)
* Routing: Revise feature requests from the community. Add affordances to match multiple path segments? Routing to sub-applications? (See also [this discussion](https://github.com/falconry/falcon/discussions/1818).) https://github.com/falconry/falcon/issues/1950
* REST: resource representation creation and consumption; [url_for](https://github.com/falconry/falcon/issues/1264) and perhaps also opt-in pydantic support?
* Affordances to support API description format generators and frontends (e.g, OpenAPI, API Blueprint) -- check community project(s) already available for Falcon?
* Better typing (mypy) support -- add type hints or stubs to the code base, and documentation examples: https://github.com/falconry/falcon/issues/1350 & https://github.com/falconry/falcon/issues/1820. See also: [PEP 484](https://www.python.org/dev/peps/pep-0484/).
* CLI: scaffolding tool?

### Docs

* Recipes: Things like how to deploy in production, how to spawn background tasks, how to make use of ASGI lifecycle events, how to do AuthN/Z, and how to handle the DAL (SQLAlchemy, [asyncpg](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html), but perhaps we can also document piccolo, et al.). What else?
* Recipes: Serverless deployments (see also: https://github.com/falconry/falcon/issues/1552)
* How to make recipes easier to find? Try to link from reference docs in more places?
* Update Dash docs for 3.x
* Recorded talk re: Intro to Falcon? Encourage people to check out doc recipes in "where to go from here" at the end of the talk.

### Performance

* Test: Benchmarking improvements (CI gate, ASGI, etc.)
* Performance: https://github.com/falconry/falcon/issues/1664 -- also for ASGI explore if it is possible to exploit cythonization to get a slight performance bump. See also: https://github.com/falconry/falcon/pull/1860#issue-571338714 -- although cythonization offered a moderate improvement in isolated benchmarks, the actual ASGI servers seem to wrap the app in a way that degrades performance to worse than pure-Python.

## 3.0.1

- [x] Bug fixes

## 3.1.0

- [x] CPython 3.10 support
- [x] Hacktoberfest contributions! :beers:
- [ ] Update benchmarks on falconframework.org
- [x] Bugfix: https://github.com/falconry/falcon/issues/1943
- [x] Doc: https://github.com/falconry/falcon/pull/1923
- [x] Doc: https://github.com/falconry/falcon/pull/1937
- [x] Doc: https://github.com/falconry/falcon/pull/1928
- [ ] Docs: Additional recipes, make recipes easier to find
- [ ] Features: url_for
- [ ] Performance: Basic WSGI perf gate - https://github.com/falconry/falcon/pull/1825 

## 3.2.0

TBD: Include 1-2 doc improvements, and one "missing feature" such as url_for or basic JWT/OAuth2 affordances that can be expanded upon in future releases. Potentially also include trio support if decided to do it and is ready.

- [ ] Performance: Basic ASGI perf gate
- [ ] Features: Baseline JWT/OAuth2 affordances and recipes 
- [ ] Better typing (mypy) support

## 3.3+

TBD: Iterate on "missing" features, trio support, doc improvements, etc. taken from themes above.

**Comment by kgriffs** [comment]
Tweaked the themes and proposed categories for point releases.

**Comment by kgriffs** [comment]
Added 3.0.2
